---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv
  labels:
    app: zookeeper
spec:
  capacity:
    storage: 5Gi  # Adjust the size based on your needs
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:  # For local testing, use hostPath; for production, consider NFS or cloud storage
    path: /mnt/data/zookeeper  # Path on the host machine

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
  labels:
    app: zookeeper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Match this with the PV's capacity
