apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-ingestion
  labels:
    app: reddit-ingestion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddit-ingestion
  template:
    metadata:
      labels:
        app: reddit-ingestion
    spec:
      containers:
      - name: reddit-ingestion
        image: <your-ecr-repository>/reddit-ingestion:v1.0.0
        ports:
        - containerPort: 8000
        env:
        # Reference values from ConfigMap
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: reddit-ingestion-config
              key: AWS_REGION
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: reddit-ingestion-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: KAFKA_TOPICS
          valueFrom:
            configMapKeyRef:
              name: reddit-ingestion-config
              key: KAFKA_TOPICS
        - name: KAFKA_GROUP_ID
          valueFrom:
            configMapKeyRef:
              name: reddit-ingestion-config
              key: KAFKA_GROUP_ID
        - name: REDDIT_USER_AGENT
          valueFrom:
            configMapKeyRef:
              name: reddit-ingestion-config
              key: REDDIT_USER_AGENT

        # Reference sensitive values from Secret
        - name: REDDIT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: reddit-ingestion-secret
              key: REDDIT_CLIENT_ID
        - name: REDDIT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: reddit-ingestion-secret
              key: REDDIT_CLIENT_SECRET
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: reddit-ingestion-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: reddit-ingestion-secret
              key: AWS_SECRET_ACCESS_KEY

        # Health probes
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

        # Resource requests and limits
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
