apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployments
  labels:
    app: deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployments
  template:
    metadata:
      labels:
        app: deployments
    spec:
      containers:
      - name: deployments
        image: bitnami/deployments:latest
        ports:
        - containerPort: 9092
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://deployments:9092"
